# Generated by Django 4.1.5 on 2023-03-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(choices=[('ey/em', 'ey/em'), ('ne/nem', 'ne/nem'), ('she/her', 'she/her'), ('they/them', 'they/them'), ('ve/ver', 've/ver'), ('xe/xem', 'xe/xem'), ('xie/xem', 'xie/xem'), ('ze/zer', 'ze/zer')], max_length=20),
        ),
    ]
