# Generated by Django 4.1.5 on 2023-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('ey/em', 'ey/em'), ('ne/nem', 'ne/nem'), ('she/her', 'she/her'), ('they/them', 'they/them'), ('ve/ver', 've/ver'), ('xe/xem', 'xe/xem'), ('xie/xem', 'xie/xem'), ('ze/zer', 'ze/zer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
