# Generated by Django 4.1.5 on 2023-03-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userprofile_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('ey/em', 'ey/em'), ('he/him', 'he/him'), ('ne/nem', 'ne/nem'), ('she/her', 'she/her'), ('they/them', 'they/them'), ('ve/ver', 've/ver'), ('xe/xem', 'xe/xem'), ('xie/xem', 'xie/xem'), ('ze/zer', 'ze/zer')], default='ey/em', max_length=20, null=True),
        ),
    ]
