# Generated by Django 4.1.5 on 2023-05-22 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavePinUser',
            new_name='OwnPinUser',
        ),
    ]
