# Generated by Django 4.1.5 on 2023-05-23 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_sharing', '0002_rename_savepinuser_ownpinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownpinuser',
            name='user_pin',
            field=models.ManyToManyField(blank=True, related_name='user_pin_chosens', to=settings.AUTH_USER_MODEL),
        ),
    ]
