# Generated by Django 4.1.5 on 2023-03-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0002_alter_pin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='destination_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(upload_to='pins'),
        ),
    ]
