# Generated by Django 4.1.5 on 2023-05-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0003_ownpinuser_user_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownpinuser',
            name='pin_id',
        ),
        migrations.RemoveField(
            model_name='ownpinuser',
            name='user_pin',
        ),
        migrations.AddField(
            model_name='ownpinuser',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_sharing.pin'),
        ),
        migrations.AlterField(
            model_name='ownpinuser',
            name='id',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True),
        ),
    ]
