# Generated by Django 4.1.5 on 2023-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0003_alter_pin_destination_link_alter_pin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
