# Generated by Django 4.1.5 on 2023-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0004_board_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pins'),
        ),
    ]
