# Generated by Django 4.1.5 on 2023-05-23 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_sharing', '0004_remove_ownpinuser_pin_id_remove_ownpinuser_user_pin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnPinUser',
            new_name='OwnPin',
        ),
    ]
