# Generated by Django 4.1.5 on 2023-05-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0005_rename_ownpinuser_ownpin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='user_pin',
            new_name='users_pin',
        ),
    ]
