# Generated by Django 4.1.5 on 2023-04-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0005_alter_pin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
