# Generated by Django 4.1.5 on 2023-05-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0006_rename_user_pin_pin_users_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='own_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_sharing.ownpin'),
        ),
    ]
