# Generated by Django 4.1.5 on 2023-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0006_alter_pin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pin_id',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
