# Generated by Django 4.1.5 on 2023-05-26 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0007_comment_own_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='own_pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_sharing.ownpin'),
        ),
    ]
