# Generated by Django 4.1.5 on 2023-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0011_pin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_id',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
