# Generated by Django 4.1.5 on 2023-05-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0012_alter_pin_pin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='user',
        ),
    ]
