# Generated by Django 4.1.5 on 2023-05-18 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_sharing', '0015_pin_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='user_pin',
            field=models.ManyToManyField(blank=True, related_name='user_pin_chosen', to=settings.AUTH_USER_MODEL),
        ),
    ]
