# Generated by Django 4.1.5 on 2023-05-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_sharing', '0016_alter_pin_user_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='user_pin',
        ),
        migrations.CreateModel(
            name='SavePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.CharField(max_length=18, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_sharing.board')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_pin', models.ManyToManyField(blank=True, related_name='user_pin_chosen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
