# Generated by Django 4.1.5 on 2023-05-18 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_sharing', '0018_remove_savepin_user_pin_pin_user_pin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavePin',
            new_name='SavePinUser',
        ),
    ]
